// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlitestore

import (
	"context"
	"time"

	"github.com/suryakencana007/tamper/audit/internal/sqlitestore/sqltypes"
)

const countAuditEventsByActionSince = `-- name: CountAuditEventsByActionSince :many
SELECT action, COUNT(*) AS count
FROM events
WHERE at > ?
GROUP BY action
ORDER BY count DESC, action ASC
`

type CountAuditEventsByActionSinceRow struct {
	Action string
	Count  int64
}

// v1.2 Sprint 2 task 03: digest body source. Counts events grouped by
// action, filtered to occurred_at > since. Sorted desc-by-count so the
// digest body's first lines are the noisiest actions. Used by the
// AuditDigestService.composeDigest path; the scheduler iterates
// opted-in cluster-admin users and calls this with their last_at
// (or users.created_at on first emit).
//
// v1.2 emits to system-cluster-admins only so the query is unscoped;
// per-cluster-scoped digests for cluster-deployer tier are v1.3 (would
// add a cluster_id IN (?...) clause, same shape as the v1.1 task 04
// ListScoped code path).
func (q *Queries) CountAuditEventsByActionSince(ctx context.Context, at time.Time) ([]CountAuditEventsByActionSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditEventsByActionSince, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditEventsByActionSinceRow{}
	for rows.Next() {
		var i CountAuditEventsByActionSinceRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEventsNotAtV4 = `-- name: CountEventsNotAtV4 :many
SELECT canonical_version, COUNT(*) AS event_count
FROM events
WHERE canonical_version <> 4
GROUP BY canonical_version
ORDER BY canonical_version ASC
`

type CountEventsNotAtV4Row struct {
	CanonicalVersion int64
	EventCount       int64
}

// Returns, per canonical_version, how many rows are NOT at version 4.
// No rows on a healthy DB. NewSQLiteLogger uses it to refuse a DB
// that holds rows this package cannot verify, and to say how many
// there are at each version: one stray row and a whole legacy file
// are different findings.
//
// The 4 is a literal on purpose. The partial index idx_events_not_v4
// (migration 006) covers exactly this predicate, and SQLite uses it
// only when the WHERE implies the index's own, which it cannot prove
// through a bound parameter. With the index the check reads only the
// rows it reports.
func (q *Queries) CountEventsNotAtV4(ctx context.Context) ([]CountEventsNotAtV4Row, error) {
	rows, err := q.db.QueryContext(ctx, countEventsNotAtV4)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsNotAtV4Row{}
	for rows.Next() {
		var i CountEventsNotAtV4Row
		if err := rows.Scan(&i.CanonicalVersion, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEventByID = `-- name: DeleteEventByID :exec
DELETE FROM events WHERE id = ?
`

// Used by the v1.5 load-fixture ConflictForce policy. Removes a single
// event by id (idempotent: zero-row deletes are not errors at the
// sqlc level). Operators invoking `barista --load-fixture
// --on-conflict=force` against an iterated fixture file rely on this
// to clear prior partial-load rows before re-inserting. Closes
// TD-INFRA-19 (v1.4 walk Step 71).
func (q *Queries) DeleteEventByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEventByID, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE id = ?
`

// Looks up a single event by id. RedactEvent uses it to tell a row
// that does not exist from a lookup that failed.
func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorUserID,
		&i.ActorEmail,
		&i.ActorIp,
		&i.ActorType,
		&i.ActorName,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ClusterID,
		&i.RequestID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.PrevHash,
		&i.Hash,
		&i.CanonicalVersion,
		&i.TenantID,
		&i.ActorTenantID,
		&i.RowSalt,
		&i.CActorEmail,
		&i.CActorName,
		&i.CActorIp,
		&i.CBefore,
		&i.CAfter,
	)
	return i, err
}

const getLatestAt = `-- name: GetLatestAt :one
SELECT at FROM events ORDER BY at DESC, canonical_version DESC, id DESC LIMIT 1
`

// v1.8 follow-up #3: returns the most-recent event's `at` value, used by
// NewSQLiteLogger to initialize the in-memory monotonic-at watermark on
// open. See audit_sqlite.go SQLiteLogger.lastAt docs.
func (q *Queries) GetLatestAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLatestAt)
	var at time.Time
	err := row.Scan(&at)
	return at, err
}

const getLatestHash = `-- name: GetLatestHash :one
SELECT hash FROM events ORDER BY at DESC, canonical_version DESC, id DESC LIMIT 1
`

// canonical_version DESC is a deterministic tiebreaker for same-at
// rows. See latestHashFrom in audit_sqlite.go.
func (q *Queries) GetLatestHash(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLatestHash)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID               string
	At               time.Time
	ActorUserID      string
	ActorEmail       string
	ActorIp          string
	ActorType        string
	ActorName        string
	Action           string
	ResourceType     string
	ResourceID       string
	ClusterID        string
	RequestID        string
	BeforeJson       string
	AfterJson        string
	PrevHash         []byte
	Hash             []byte
	CanonicalVersion int64
	TenantID         string
	ActorTenantID    string
	RowSalt          sqltypes.Blob
	CActorEmail      sqltypes.Blob
	CActorName       sqltypes.Blob
	CActorIp         sqltypes.Blob
	CBefore          sqltypes.Blob
	CAfter           sqltypes.Blob
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.At,
		arg.ActorUserID,
		arg.ActorEmail,
		arg.ActorIp,
		arg.ActorType,
		arg.ActorName,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ClusterID,
		arg.RequestID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.PrevHash,
		arg.Hash,
		arg.CanonicalVersion,
		arg.TenantID,
		arg.ActorTenantID,
		arg.RowSalt,
		arg.CActorEmail,
		arg.CActorName,
		arg.CActorIp,
		arg.CBefore,
		arg.CAfter,
	)
	return err
}

const listEventsByTenant = `-- name: ListEventsByTenant :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE tenant_id = ?
ORDER BY at ASC, canonical_version ASC, id ASC
`

// Phase 7 (7i-1): the tenant-scoped export projection. Oldest first: an
// export is read as a narrative, unlike the paged admin views which are
// newest-first. Ordering mirrors the verify walk's tiebreak so an export
// and a chain walk agree on row order.
func (q *Queries) ListEventsByTenant(ctx context.Context, tenantID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForVerify = `-- name: ListEventsForVerify :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
ORDER BY at ASC, canonical_version ASC, id ASC
`

// v1.8 Sprint 0 follow-up (TD-AUDIT-12): canonical_version ASC is the
// deterministic tiebreaker for same-at rows. See verify_boot.go's
// package docs for the rationale + observed flake rate.
func (q *Queries) ListEventsForVerify(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForVerify)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOlderThan = `-- name: PruneOlderThan :execrows
DELETE FROM events WHERE at < ?
`

func (q *Queries) PruneOlderThan(ctx context.Context, at time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneOlderThan, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const redactEventPII = `-- name: RedactEventPII :exec
UPDATE events
SET actor_email = '',
    actor_name  = '',
    actor_ip    = '',
    before_json = '',
    after_json  = '',
    row_salt    = x''
WHERE id = ? AND canonical_version = 4
`

// Phase 7 (7i-1): erasure in place. Clears the plaintext and ZEROES the
// salt; the c_* commitment columns are deliberately untouched because
// they are what the canonical payload hashed, so changing them would
// break the chain in exactly the way the commitment scheme avoids.
// Scoped to canonical_version=4: a pre-v4 row hashed its PII directly,
// so there is nothing to redact without breaking its hash.
// NOTE: keep these comments ASCII-only. sqlc mis-computes byte offsets
// around multi-byte characters and silently TRUNCATES the generated SQL
// (it produced "canonical_versio" and a stray "C;" from an em dash).
func (q *Queries) RedactEventPII(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, redactEventPII, id)
	return err
}
