// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitestore

import (
	"context"
	"time"
)

type Querier interface {
	// v1.2 Sprint 2 task 03: digest body source. Counts events grouped by
	// action, filtered to occurred_at > since. Sorted desc-by-count so the
	// digest body's first lines are the noisiest actions. Used by the
	// AuditDigestService.composeDigest path; the scheduler iterates
	// opted-in cluster-admin users and calls this with their last_at
	// (or users.created_at on first emit).
	//
	// v1.2 emits to system-cluster-admins only so the query is unscoped;
	// per-cluster-scoped digests for cluster-deployer tier are v1.3 (would
	// add a cluster_id IN (?...) clause, same shape as the v1.1 task 04
	// ListScoped code path).
	CountAuditEventsByActionSince(ctx context.Context, at time.Time) ([]CountAuditEventsByActionSinceRow, error)
	// Used by the boot path to decide whether to insert the v1.0 chain
	// restart genesis row. Caller passes the canonical version (2) to
	// count. Zero count on a fresh v1.0 boot (or a v0.9 upgrade) means
	// the boot path will insert the genesis row; non-zero means a prior
	// boot already inserted it.
	CountChainRestartV2(ctx context.Context, canonicalVersion int64) (int64, error)
	CountEvents(ctx context.Context) (int64, error)
	// Counts every row whose action column equals the given string. Used by
	// HasChainMigrate (v1.5 task 01) to check for an existing
	// system.audit.chain_migrate marker on boot so the encoder migration is
	// idempotent across pod restarts.
	CountEventsByAction(ctx context.Context, action string) (int64, error)
	// Returns per-canonical-version row counts across the whole audit DB.
	// Used by `barista audit verify` to print the distribution summary
	// ("canonical_version=2: 3, canonical_version=3: 9") after a clean
	// walk, so operators can sanity-check what segment shapes their DB
	// carries. Sorted by canonical_version ASC so the output is stable.
	CountEventsByCanonicalVersion(ctx context.Context) ([]CountEventsByCanonicalVersionRow, error)
	// Used by the v1.5 load-fixture ConflictForce policy. Removes a single
	// event by id (idempotent: zero-row deletes are not errors at the
	// sqlc level). Operators invoking `barista --load-fixture
	// --on-conflict=force` against an iterated fixture file rely on this
	// to clear prior partial-load rows before re-inserting. Closes
	// TD-INFRA-19 (v1.4 walk Step 71).
	DeleteEventByID(ctx context.Context, id string) error
	// Used by the --from-id walker-anchor flag (v1.4 - TD-AUDIT-10). Looks
	// up a single event by id so VerifyLegacy can validate the row exists
	// + carries the expected canonical_version before walking from it.
	GetEventByID(ctx context.Context, id string) (Event, error)
	// v1.8 follow-up #3: returns the most-recent event's `at` value, used by
	// NewSQLiteLogger to initialize the in-memory monotonic-at watermark on
	// open. See audit_sqlite.go SQLiteLogger.lastAt docs.
	GetLatestAt(ctx context.Context) (time.Time, error)
	// Returns the most-recent chain-restart event. Caller passes the
	// action string (audit.ActionAuditChainRestart) so sqlc doesn't
	// see the dotted literal inline. Used by `barista audit verify`
	// to identify the latest chain genesis row when multiple
	// canonical-version segments live in the same DB.
	GetLatestChainRestart(ctx context.Context, action string) (Event, error)
	// Returns the most-recent chain-restart event at a specific
	// canonical_version. Used by `barista audit verify --legacy
	// --canonical-version=N` to walk the v1.0 (canonical_version=2)
	// segment in isolation when both v2 + v3 genesis rows are present.
	GetLatestChainRestartAtVersion(ctx context.Context, arg GetLatestChainRestartAtVersionParams) (Event, error)
	// v1.8 follow-up #2: canonical_version DESC is the deterministic
	// tiebreaker for same-at rows. See audit_sqlite.go latestHash() docs.
	GetLatestHash(ctx context.Context) ([]byte, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	ListEventsAll(ctx context.Context, limit int64) ([]Event, error)
	ListEventsBefore(ctx context.Context, arg ListEventsBeforeParams) ([]Event, error)
	ListEventsByActor(ctx context.Context, arg ListEventsByActorParams) ([]Event, error)
	// Returns every event at the given canonical_version in chain-ascending
	// order. Used by VerifyLegacy(N, "") - the v1.4 fix shape (TD-AUDIT-10)
	// closes the walk-window-scoping issue where loaded fixture events
	// with older timestamps fell behind the walker's starting point.
	ListEventsByCanonicalVersion(ctx context.Context, canonicalVersion int64) ([]Event, error)
	ListEventsByRequest(ctx context.Context, arg ListEventsByRequestParams) ([]Event, error)
	ListEventsByResource(ctx context.Context, arg ListEventsByResourceParams) ([]Event, error)
	// Phase 7 (7i-1): the tenant-scoped export projection. Oldest first: an
	// export is read as a narrative, unlike the paged admin views which are
	// newest-first. Ordering mirrors the verify walk's tiebreak so an export
	// and a chain walk agree on row order.
	ListEventsByTenant(ctx context.Context, tenantID string) ([]Event, error)
	// v1.8 Sprint 0 follow-up (TD-AUDIT-12): canonical_version ASC is the
	// deterministic tiebreaker for same-at rows. See verify_boot.go's
	// package docs for the rationale + observed flake rate.
	ListEventsForVerify(ctx context.Context) ([]Event, error)
	// Walks the chain segment starting at the most-recent
	// system.audit.chain_restart row. The dispatcher picks the row's
	// (at, id), then this query returns every event from that row forward
	// (inclusive) in ascending chain order. Used by `barista audit verify`
	// to walk the v1.0+ chain when older-shape rows still live alongside.
	ListEventsForVerifyFromChainRestart(ctx context.Context, arg ListEventsForVerifyFromChainRestartParams) ([]Event, error)
	// Returns audit rows that aren't scoped to any cluster (cluster_id =
	// '': auth.*, system.*, anything the middleware emits without stamping
	// a cluster_id). Used as the degenerate-case fallback by the v1.1 task
	// 04 ListScoped path when the caller has zero reachable clusters - the
	// code-side IN clause cannot bind a zero-element slice, so we route
	// to this query instead.
	ListEventsNonClusterScoped(ctx context.Context, limit int64) ([]Event, error)
	// Cursor-paginated variant of ListEventsNonClusterScoped.
	ListEventsNonClusterScopedBefore(ctx context.Context, arg ListEventsNonClusterScopedBeforeParams) ([]Event, error)
	PruneOlderThan(ctx context.Context, at time.Time) (int64, error)
	// Phase 7 (7i-1): erasure in place. Clears the plaintext and ZEROES the
	// salt; the c_* commitment columns are deliberately untouched because
	// they are what the canonical payload hashed, so changing them would
	// break the chain in exactly the way the commitment scheme avoids.
	// Scoped to canonical_version=4: a pre-v4 row hashed its PII directly,
	// so there is nothing to redact without breaking its hash.
	// NOTE: keep these comments ASCII-only. sqlc mis-computes byte offsets
	// around multi-byte characters and silently TRUNCATES the generated SQL
	// (it produced "canonical_versio" and a stray "C;" from an em dash).
	RedactEventPII(ctx context.Context, id string) error
	// Used by the v1.5 audit-chain encoder migration (audit.MigrateLegacyV2Hashes).
	// Writes the recomputed hash + prev_hash for a single existing event,
	// leaving every other column unchanged. The migration walks v=2 rows
	// in chain order; each row's recomputed hash becomes the next row's
	// prev_hash so the migrated chain stays self-consistent.
	//
	// Idempotent on re-run: the WHERE id = ? clause matches at most one
	// row; re-running with the same hash + prev_hash is a no-op write.
	UpdateEventHash(ctx context.Context, arg UpdateEventHashParams) error
}

var _ Querier = (*Queries)(nil)
