// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitestore

import (
	"context"
	"time"
)

type Querier interface {
	// v1.2 Sprint 2 task 03: digest body source. Counts events grouped by
	// action, filtered to occurred_at > since. Sorted desc-by-count so the
	// digest body's first lines are the noisiest actions. Used by the
	// AuditDigestService.composeDigest path; the scheduler iterates
	// opted-in cluster-admin users and calls this with their last_at
	// (or users.created_at on first emit).
	//
	// v1.2 emits to system-cluster-admins only so the query is unscoped;
	// per-cluster-scoped digests for cluster-deployer tier are v1.3 (would
	// add a cluster_id IN (?...) clause, same shape as the v1.1 task 04
	// ListScoped code path).
	CountAuditEventsByActionSince(ctx context.Context, at time.Time) ([]CountAuditEventsByActionSinceRow, error)
	// Returns, per canonical_version, how many rows are NOT at version 4.
	// No rows on a healthy DB. NewSQLiteLogger uses it to refuse a DB
	// that holds rows this package cannot verify, and to say how many
	// there are at each version: one stray row and a whole legacy file
	// are different findings.
	//
	// The 4 is a literal on purpose. The partial index idx_events_not_v4
	// (migration 006) covers exactly this predicate, and SQLite uses it
	// only when the WHERE implies the index's own, which it cannot prove
	// through a bound parameter. With the index the check reads only the
	// rows it reports.
	CountEventsNotAtV4(ctx context.Context) ([]CountEventsNotAtV4Row, error)
	// Used by the v1.5 load-fixture ConflictForce policy. Removes a single
	// event by id (idempotent: zero-row deletes are not errors at the
	// sqlc level). Operators invoking `barista --load-fixture
	// --on-conflict=force` against an iterated fixture file rely on this
	// to clear prior partial-load rows before re-inserting. Closes
	// TD-INFRA-19 (v1.4 walk Step 71).
	DeleteEventByID(ctx context.Context, id string) error
	// Looks up a single event by id. RedactEvent uses it to tell a row
	// that does not exist from a lookup that failed.
	GetEventByID(ctx context.Context, id string) (Event, error)
	// v1.8 follow-up #3: returns the most-recent event's `at` value, used by
	// NewSQLiteLogger to initialize the in-memory monotonic-at watermark on
	// open. See audit_sqlite.go SQLiteLogger.lastAt docs.
	GetLatestAt(ctx context.Context) (time.Time, error)
	// canonical_version DESC is a deterministic tiebreaker for same-at
	// rows. See latestHashFrom in audit_sqlite.go.
	GetLatestHash(ctx context.Context) ([]byte, error)
	InsertEvent(ctx context.Context, arg InsertEventParams) error
	// Phase 7 (7i-1): the tenant-scoped export projection. Oldest first: an
	// export is read as a narrative, unlike the paged admin views which are
	// newest-first. Ordering mirrors the verify walk's tiebreak so an export
	// and a chain walk agree on row order.
	ListEventsByTenant(ctx context.Context, tenantID string) ([]Event, error)
	// v1.8 Sprint 0 follow-up (TD-AUDIT-12): canonical_version ASC is the
	// deterministic tiebreaker for same-at rows. See verify_boot.go's
	// package docs for the rationale + observed flake rate.
	ListEventsForVerify(ctx context.Context) ([]Event, error)
	PruneOlderThan(ctx context.Context, at time.Time) (int64, error)
	// Phase 7 (7i-1): erasure in place. Clears the plaintext and ZEROES the
	// salt; the c_* commitment columns are deliberately untouched because
	// they are what the canonical payload hashed, so changing them would
	// break the chain in exactly the way the commitment scheme avoids.
	// Scoped to canonical_version=4: a pre-v4 row hashed its PII directly,
	// so there is nothing to redact without breaking its hash.
	// NOTE: keep these comments ASCII-only. sqlc mis-computes byte offsets
	// around multi-byte characters and silently TRUNCATES the generated SQL
	// (it produced "canonical_versio" and a stray "C;" from an em dash).
	RedactEventPII(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
