// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlitestore

import (
	"context"
	"time"
)

const countAuditEventsByActionSince = `-- name: CountAuditEventsByActionSince :many
SELECT action, COUNT(*) AS count
FROM events
WHERE at > ?
GROUP BY action
ORDER BY count DESC, action ASC
`

type CountAuditEventsByActionSinceRow struct {
	Action string
	Count  int64
}

// v1.2 Sprint 2 task 03: digest body source. Counts events grouped by
// action, filtered to occurred_at > since. Sorted desc-by-count so the
// digest body's first lines are the noisiest actions. Used by the
// AuditDigestService.composeDigest path; the scheduler iterates
// opted-in cluster-admin users and calls this with their last_at
// (or users.created_at on first emit).
//
// v1.2 emits to system-cluster-admins only so the query is unscoped;
// per-cluster-scoped digests for cluster-deployer tier are v1.3 (would
// add a cluster_id IN (?...) clause, same shape as the v1.1 task 04
// ListScoped code path).
func (q *Queries) CountAuditEventsByActionSince(ctx context.Context, at time.Time) ([]CountAuditEventsByActionSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, countAuditEventsByActionSince, at)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountAuditEventsByActionSinceRow{}
	for rows.Next() {
		var i CountAuditEventsByActionSinceRow
		if err := rows.Scan(&i.Action, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countChainRestartV2 = `-- name: CountChainRestartV2 :one
SELECT COUNT(*) FROM events WHERE canonical_version = ?
`

// Used by the boot path to decide whether to insert the v1.0 chain
// restart genesis row. Caller passes the canonical version (2) to
// count. Zero count on a fresh v1.0 boot (or a v0.9 upgrade) means
// the boot path will insert the genesis row; non-zero means a prior
// boot already inserted it.
func (q *Queries) CountChainRestartV2(ctx context.Context, canonicalVersion int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChainRestartV2, canonicalVersion)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEvents = `-- name: CountEvents :one
SELECT COUNT(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByAction = `-- name: CountEventsByAction :one
SELECT COUNT(*) FROM events WHERE action = ?
`

// Counts every row whose action column equals the given string. Used by
// HasChainMigrate (v1.5 task 01) to check for an existing
// system.audit.chain_migrate marker on boot so the encoder migration is
// idempotent across pod restarts.
func (q *Queries) CountEventsByAction(ctx context.Context, action string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByAction, action)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByCanonicalVersion = `-- name: CountEventsByCanonicalVersion :many
SELECT canonical_version, COUNT(*) AS event_count
FROM events
GROUP BY canonical_version
ORDER BY canonical_version ASC
`

type CountEventsByCanonicalVersionRow struct {
	CanonicalVersion int64
	EventCount       int64
}

// Returns per-canonical-version row counts across the whole audit DB.
// Used by `barista audit verify` to print the distribution summary
// ("canonical_version=2: 3, canonical_version=3: 9") after a clean
// walk, so operators can sanity-check what segment shapes their DB
// carries. Sorted by canonical_version ASC so the output is stable.
func (q *Queries) CountEventsByCanonicalVersion(ctx context.Context) ([]CountEventsByCanonicalVersionRow, error) {
	rows, err := q.db.QueryContext(ctx, countEventsByCanonicalVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByCanonicalVersionRow{}
	for rows.Next() {
		var i CountEventsByCanonicalVersionRow
		if err := rows.Scan(&i.CanonicalVersion, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEventByID = `-- name: DeleteEventByID :exec
DELETE FROM events WHERE id = ?
`

// Used by the v1.5 load-fixture ConflictForce policy. Removes a single
// event by id (idempotent: zero-row deletes are not errors at the
// sqlc level). Operators invoking `barista --load-fixture
// --on-conflict=force` against an iterated fixture file rely on this
// to clear prior partial-load rows before re-inserting. Closes
// TD-INFRA-19 (v1.4 walk Step 71).
func (q *Queries) DeleteEventByID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEventByID, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE id = ?
`

// Used by the --from-id walker-anchor flag (v1.4 - TD-AUDIT-10). Looks
// up a single event by id so VerifyLegacy can validate the row exists
// + carries the expected canonical_version before walking from it.
func (q *Queries) GetEventByID(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorUserID,
		&i.ActorEmail,
		&i.ActorIp,
		&i.ActorType,
		&i.ActorName,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ClusterID,
		&i.RequestID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.PrevHash,
		&i.Hash,
		&i.CanonicalVersion,
		&i.TenantID,
		&i.ActorTenantID,
		&i.RowSalt,
		&i.CActorEmail,
		&i.CActorName,
		&i.CActorIp,
		&i.CBefore,
		&i.CAfter,
	)
	return i, err
}

const getLatestAt = `-- name: GetLatestAt :one
SELECT at FROM events ORDER BY at DESC, canonical_version DESC, id DESC LIMIT 1
`

// v1.8 follow-up #3: returns the most-recent event's `at` value, used by
// NewSQLiteLogger to initialize the in-memory monotonic-at watermark on
// open. See audit_sqlite.go SQLiteLogger.lastAt docs.
func (q *Queries) GetLatestAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLatestAt)
	var at time.Time
	err := row.Scan(&at)
	return at, err
}

const getLatestChainRestart = `-- name: GetLatestChainRestart :one
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE action = ?
ORDER BY at DESC, canonical_version DESC, id DESC
LIMIT 1
`

// Returns the most-recent chain-restart event. Caller passes the
// action string (audit.ActionAuditChainRestart) so sqlc doesn't
// see the dotted literal inline. Used by `barista audit verify`
// to identify the latest chain genesis row when multiple
// canonical-version segments live in the same DB.
func (q *Queries) GetLatestChainRestart(ctx context.Context, action string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getLatestChainRestart, action)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorUserID,
		&i.ActorEmail,
		&i.ActorIp,
		&i.ActorType,
		&i.ActorName,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ClusterID,
		&i.RequestID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.PrevHash,
		&i.Hash,
		&i.CanonicalVersion,
		&i.TenantID,
		&i.ActorTenantID,
		&i.RowSalt,
		&i.CActorEmail,
		&i.CActorName,
		&i.CActorIp,
		&i.CBefore,
		&i.CAfter,
	)
	return i, err
}

const getLatestChainRestartAtVersion = `-- name: GetLatestChainRestartAtVersion :one
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE action = ? AND canonical_version = ?
ORDER BY at DESC, id DESC
LIMIT 1
`

type GetLatestChainRestartAtVersionParams struct {
	Action           string
	CanonicalVersion int64
}

// Returns the most-recent chain-restart event at a specific
// canonical_version. Used by `barista audit verify --legacy
// --canonical-version=N` to walk the v1.0 (canonical_version=2)
// segment in isolation when both v2 + v3 genesis rows are present.
func (q *Queries) GetLatestChainRestartAtVersion(ctx context.Context, arg GetLatestChainRestartAtVersionParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getLatestChainRestartAtVersion, arg.Action, arg.CanonicalVersion)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.At,
		&i.ActorUserID,
		&i.ActorEmail,
		&i.ActorIp,
		&i.ActorType,
		&i.ActorName,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.ClusterID,
		&i.RequestID,
		&i.BeforeJson,
		&i.AfterJson,
		&i.PrevHash,
		&i.Hash,
		&i.CanonicalVersion,
		&i.TenantID,
		&i.ActorTenantID,
		&i.RowSalt,
		&i.CActorEmail,
		&i.CActorName,
		&i.CActorIp,
		&i.CBefore,
		&i.CAfter,
	)
	return i, err
}

const getLatestHash = `-- name: GetLatestHash :one
SELECT hash FROM events ORDER BY at DESC, canonical_version DESC, id DESC LIMIT 1
`

// v1.8 follow-up #2: canonical_version DESC is the deterministic
// tiebreaker for same-at rows. See audit_sqlite.go latestHash() docs.
func (q *Queries) GetLatestHash(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLatestHash)
	var hash []byte
	err := row.Scan(&hash)
	return hash, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	ID               string
	At               time.Time
	ActorUserID      string
	ActorEmail       string
	ActorIp          string
	ActorType        string
	ActorName        string
	Action           string
	ResourceType     string
	ResourceID       string
	ClusterID        string
	RequestID        string
	BeforeJson       string
	AfterJson        string
	PrevHash         []byte
	Hash             []byte
	CanonicalVersion int64
	TenantID         string
	ActorTenantID    string
	RowSalt          []byte
	CActorEmail      []byte
	CActorName       []byte
	CActorIp         []byte
	CBefore          []byte
	CAfter           []byte
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.ID,
		arg.At,
		arg.ActorUserID,
		arg.ActorEmail,
		arg.ActorIp,
		arg.ActorType,
		arg.ActorName,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.ClusterID,
		arg.RequestID,
		arg.BeforeJson,
		arg.AfterJson,
		arg.PrevHash,
		arg.Hash,
		arg.CanonicalVersion,
		arg.TenantID,
		arg.ActorTenantID,
		arg.RowSalt,
		arg.CActorEmail,
		arg.CActorName,
		arg.CActorIp,
		arg.CBefore,
		arg.CAfter,
	)
	return err
}

const listEventsAll = `-- name: ListEventsAll :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
ORDER BY at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListEventsAll(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsAll, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsBefore = `-- name: ListEventsBefore :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE at < ?
   OR (at = ? AND id < ?)
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsBeforeParams struct {
	At    time.Time
	At_2  time.Time
	ID    string
	Limit int64
}

func (q *Queries) ListEventsBefore(ctx context.Context, arg ListEventsBeforeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBefore,
		arg.At,
		arg.At_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByActor = `-- name: ListEventsByActor :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE actor_user_id = ?
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsByActorParams struct {
	ActorUserID string
	Limit       int64
}

func (q *Queries) ListEventsByActor(ctx context.Context, arg ListEventsByActorParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByActor, arg.ActorUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCanonicalVersion = `-- name: ListEventsByCanonicalVersion :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE canonical_version = ?
ORDER BY at ASC, id ASC
`

// Returns every event at the given canonical_version in chain-ascending
// order. Used by VerifyLegacy(N, "") - the v1.4 fix shape (TD-AUDIT-10)
// closes the walk-window-scoping issue where loaded fixture events
// with older timestamps fell behind the walker's starting point.
func (q *Queries) ListEventsByCanonicalVersion(ctx context.Context, canonicalVersion int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByCanonicalVersion, canonicalVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByRequest = `-- name: ListEventsByRequest :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE request_id = ?
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsByRequestParams struct {
	RequestID string
	Limit     int64
}

func (q *Queries) ListEventsByRequest(ctx context.Context, arg ListEventsByRequestParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByRequest, arg.RequestID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByResource = `-- name: ListEventsByResource :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE resource_type = ? AND resource_id = ?
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsByResourceParams struct {
	ResourceType string
	ResourceID   string
	Limit        int64
}

func (q *Queries) ListEventsByResource(ctx context.Context, arg ListEventsByResourceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByResource, arg.ResourceType, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTenant = `-- name: ListEventsByTenant :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE tenant_id = ?
ORDER BY at ASC, canonical_version ASC, id ASC
`

// Phase 7 (7i-1): the tenant-scoped export projection. Oldest first: an
// export is read as a narrative, unlike the paged admin views which are
// newest-first. Ordering mirrors the verify walk's tiebreak so an export
// and a chain walk agree on row order.
func (q *Queries) ListEventsByTenant(ctx context.Context, tenantID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForVerify = `-- name: ListEventsForVerify :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
ORDER BY at ASC, canonical_version ASC, id ASC
`

// v1.8 Sprint 0 follow-up (TD-AUDIT-12): canonical_version ASC is the
// deterministic tiebreaker for same-at rows. See verify_boot.go's
// package docs for the rationale + observed flake rate.
func (q *Queries) ListEventsForVerify(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForVerify)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForVerifyFromChainRestart = `-- name: ListEventsForVerifyFromChainRestart :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE at > ? OR (at = ? AND id >= ?)
ORDER BY at ASC, id ASC
`

type ListEventsForVerifyFromChainRestartParams struct {
	At   time.Time
	At_2 time.Time
	ID   string
}

// Walks the chain segment starting at the most-recent
// system.audit.chain_restart row. The dispatcher picks the row's
// (at, id), then this query returns every event from that row forward
// (inclusive) in ascending chain order. Used by `barista audit verify`
// to walk the v1.0+ chain when older-shape rows still live alongside.
func (q *Queries) ListEventsForVerifyFromChainRestart(ctx context.Context, arg ListEventsForVerifyFromChainRestartParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsForVerifyFromChainRestart, arg.At, arg.At_2, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsNonClusterScoped = `-- name: ListEventsNonClusterScoped :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE cluster_id = ''
ORDER BY at DESC, id DESC
LIMIT ?
`

// Returns audit rows that aren't scoped to any cluster (cluster_id =
// ”: auth.*, system.*, anything the middleware emits without stamping
// a cluster_id). Used as the degenerate-case fallback by the v1.1 task
// 04 ListScoped path when the caller has zero reachable clusters - the
// code-side IN clause cannot bind a zero-element slice, so we route
// to this query instead.
func (q *Queries) ListEventsNonClusterScoped(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsNonClusterScoped, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsNonClusterScopedBefore = `-- name: ListEventsNonClusterScopedBefore :many
SELECT
    id, at, actor_user_id, actor_email, actor_ip, actor_type, actor_name,
    action, resource_type, resource_id, cluster_id, request_id,
    before_json, after_json, prev_hash, hash, canonical_version,
    tenant_id, actor_tenant_id, row_salt,
    c_actor_email, c_actor_name, c_actor_ip, c_before, c_after
FROM events
WHERE cluster_id = ''
  AND (at < ? OR (at = ? AND id < ?))
ORDER BY at DESC, id DESC
LIMIT ?
`

type ListEventsNonClusterScopedBeforeParams struct {
	At    time.Time
	At_2  time.Time
	ID    string
	Limit int64
}

// Cursor-paginated variant of ListEventsNonClusterScoped.
func (q *Queries) ListEventsNonClusterScopedBefore(ctx context.Context, arg ListEventsNonClusterScopedBeforeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsNonClusterScopedBefore,
		arg.At,
		arg.At_2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.At,
			&i.ActorUserID,
			&i.ActorEmail,
			&i.ActorIp,
			&i.ActorType,
			&i.ActorName,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.ClusterID,
			&i.RequestID,
			&i.BeforeJson,
			&i.AfterJson,
			&i.PrevHash,
			&i.Hash,
			&i.CanonicalVersion,
			&i.TenantID,
			&i.ActorTenantID,
			&i.RowSalt,
			&i.CActorEmail,
			&i.CActorName,
			&i.CActorIp,
			&i.CBefore,
			&i.CAfter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneOlderThan = `-- name: PruneOlderThan :execrows
DELETE FROM events WHERE at < ?
`

func (q *Queries) PruneOlderThan(ctx context.Context, at time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneOlderThan, at)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const redactEventPII = `-- name: RedactEventPII :exec
UPDATE events
SET actor_email = '',
    actor_name  = '',
    actor_ip    = '',
    before_json = '',
    after_json  = '',
    row_salt    = x''
WHERE id = ? AND canonical_version = 4
`

// Phase 7 (7i-1): erasure in place. Clears the plaintext and ZEROES the
// salt; the c_* commitment columns are deliberately untouched because
// they are what the canonical payload hashed, so changing them would
// break the chain in exactly the way the commitment scheme avoids.
// Scoped to canonical_version=4: a pre-v4 row hashed its PII directly,
// so there is nothing to redact without breaking its hash.
// NOTE: keep these comments ASCII-only. sqlc mis-computes byte offsets
// around multi-byte characters and silently TRUNCATES the generated SQL
// (it produced "canonical_versio" and a stray "C;" from an em dash).
func (q *Queries) RedactEventPII(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, redactEventPII, id)
	return err
}

const updateEventHash = `-- name: UpdateEventHash :exec
UPDATE events
SET hash = ?, prev_hash = ?
WHERE id = ?
`

type UpdateEventHashParams struct {
	Hash     []byte
	PrevHash []byte
	ID       string
}

// Used by the v1.5 audit-chain encoder migration (audit.MigrateLegacyV2Hashes).
// Writes the recomputed hash + prev_hash for a single existing event,
// leaving every other column unchanged. The migration walks v=2 rows
// in chain order; each row's recomputed hash becomes the next row's
// prev_hash so the migrated chain stays self-consistent.
//
// Idempotent on re-run: the WHERE id = ? clause matches at most one
// row; re-running with the same hash + prev_hash is a no-op write.
func (q *Queries) UpdateEventHash(ctx context.Context, arg UpdateEventHashParams) error {
	_, err := q.db.ExecContext(ctx, updateEventHash, arg.Hash, arg.PrevHash, arg.ID)
	return err
}
