// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlitestore

import (
	"time"
)

type Event struct {
	ID               string
	At               time.Time
	ActorUserID      string
	ActorEmail       string
	ActorIp          string
	ActorType        string
	ActorName        string
	Action           string
	ResourceType     string
	ResourceID       string
	ClusterID        string
	RequestID        string
	BeforeJson       string
	AfterJson        string
	PrevHash         []byte
	Hash             []byte
	CanonicalVersion int64
}
